/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.InsuranceJPanels;

import Business.Business;
import Insurance.InsuranceAgent;
import Insurance.InsuranceAgentDirectory;
import Insurance.InsuranceEnrollment;
import UI.MainJFrame;
import UserAccount.UserAccount;
import java.awt.GridLayout;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divya
 */
public class InsuranceAdminRoleJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsuranceAdminRole
     */
    public Business business;

    public UserAccount userAccount;
    DefaultTableModel insPlansTableModel;
    DefaultTableModel ApplicantModel;

    public InsuranceAdminRoleJFrame() {
        initComponents();
        this.insPlansTableModel = (DefaultTableModel) insEnrollmentsTable.getModel();
        this.ApplicantModel = (DefaultTableModel) applicantDetailsTable.getModel();

        displayInsurancePlans();
        polulateApplicantTable();
    }

    public InsuranceAdminRoleJFrame(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.setVisible(true);
        this.insPlansTableModel = (DefaultTableModel) insEnrollmentsTable.getModel();
        this.ApplicantModel = (DefaultTableModel) applicantDetailsTable.getModel();

        displayInsurancePlans();
        polulateApplicantTable();
    }

    public void displayInsurancePlans() {
        ArrayList<InsuranceEnrollment> ips = this.business.getInsuranceEnrollmentRequests().getEnrollments();
        if (ips.size() >= 0) {
            insPlansTableModel.setRowCount(0);
            for (InsuranceEnrollment h : ips) {
                Object row[] = new Object[5];
                row[0] = h.getEnrollmentId();
                row[1] = h.getPatient().getId();
                row[2] = h.getPatient().getFirstName() + ' ' + h.getPatient().getLastName();
                row[3] = h.getInsurancePlan().getPlanName();
                row[4] = h.getStatus();
                insPlansTableModel.addRow(row);
            }
        }
    }

    public void polulateApplicantTable() {
        ArrayList<InsuranceAgent> ips = this.business.getInsuranceAgents().getInsuranceAgents();
        if (ips.size() >= 0) {
            ApplicantModel.setRowCount(0);

            for (InsuranceAgent h : this.business.getInsuranceAgents().getInsuranceAgents()) {
                Object row[] = new Object[6];
                row[0] = h.getId();
                row[1] = h.getFirstName();
                row[2] = h.getLastName();
                row[3] = h.getEmail();
                row[4] = h.getPhoneNumber();
                row[5] = h.getAddress();
                

                ApplicantModel.addRow(row);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        applicantDetailsTable = new javax.swing.JTable();
        UpdateBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        insEnrollmentsTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hospital Management System");
        jPanel2.add(jLabel5);

        applicantDetailsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "agent Id", "First Name", "Last Name", "Email Id", "PhoneNumber", "Address"
            }
        ));
        jScrollPane2.setViewportView(applicantDetailsTable);

        UpdateBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        UpdateBtn.setText("Update");
        UpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        insEnrollmentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Enrollment ID", "Patient ID", "PatientName", "Plan Name", "Status"
            }
        ));
        jScrollPane3.setViewportView(insEnrollmentsTable);

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setText("Insurance Enrollments");

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel2.setText("Applicants");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(UpdateBtn)
                .addGap(142, 142, 142)
                .addComponent(DeleteBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(166, 166, 166))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 349, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateBtn)
                    .addComponent(DeleteBtn))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(business);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
try{
        int selectedRow = applicantDetailsTable.getSelectedRow();
    System.out.println("Selected Row: " + selectedRow); // Debugging statement
    if (selectedRow >= 0) {
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Would you like to delete the data?", "Warning", dialogBtn);
        if (dialogResult == JOptionPane.YES_OPTION) {
            String agentId = applicantDetailsTable.getValueAt(selectedRow, 0).toString();
             InsuranceAgent h = business.getInsuranceAgents().findInsuranceAgent(agentId);
           // InsuranceAgent h = (InsuranceAgent) applicantDetailsTable.getValueAt(selectedRow, 0).toString();
            System.out.println("Insurance Agent: " + h); // Debugging statement
            UserAccount ua = this.business.getTopLevelUserAccountDirectory().getUserAccountByPersonId(h.getId());
            System.out.println("User Account: " + ua); // Debugging statement
            if (ua != null) {
                this.business.getTopLevelUserAccountDirectory().getUseraccountList().remove(ua);
                this.business.getInsuranceAgents().deleteAgent(h);
                ApplicantModel.removeRow(selectedRow);
                polulateApplicantTable();
            } else {
                JOptionPane.showMessageDialog(null, "User account for this insurance agent does not exist.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(null, "Select a Row");
    }
    } catch (Exception ex) {
ex.printStackTrace();
JOptionPane.showMessageDialog(null, "Error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}
       
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void UpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtnActionPerformed
        // TODO add your handling code here:
     try{
        int selectedRow = applicantDetailsTable.getSelectedRow();
        if (selectedRow >= 0) {
            String agentId = applicantDetailsTable.getValueAt(selectedRow, 0).toString();
            InsuranceAgent agent = this.business.getInsuranceAgents().findInsuranceAgent(agentId);

            // Display the agent details in a dialog box
            JTextField firstNameField = new JTextField(agent.getFirstName());
            JTextField lastNameField = new JTextField(agent.getLastName());
            JTextField emailField = new JTextField(agent.getEmail());
            JTextField phoneField = new JTextField(agent.getPhoneNumber());
            JTextField addressField = new JTextField(agent.getAddress());

            JPanel panel = new JPanel(new GridLayout(0, 1));
            panel.add(new JLabel("First Name:"));
            panel.add(firstNameField);
            panel.add(new JLabel("Last Name:"));
            panel.add(lastNameField);
            panel.add(new JLabel("Email:"));
            panel.add(emailField);
            panel.add(new JLabel("Phone Number:"));
            panel.add(phoneField);
            panel.add(new JLabel("Address:"));
            panel.add(addressField);

            int result = JOptionPane.showConfirmDialog(null, panel, "Update Agent Details", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            
            if (result == JOptionPane.OK_OPTION) {
                // Validate the inputs
                if (firstNameField.getText().isEmpty() || lastNameField.getText().isEmpty() || emailField.getText().isEmpty() || phoneField.getText().isEmpty() || addressField.getText().isEmpty()) {
                    JOptionPane.showMessageDialog(null, "Please enter values for all fields", "Error", JOptionPane.ERROR_MESSAGE);
                } else {
            
                // Update the agent details
                agent.setFirstName(firstNameField.getText());
                agent.setLastName(lastNameField.getText());
                agent.setEmail(emailField.getText());
                agent.setPhoneNumber(phoneField.getText());
                agent.setAddress(addressField.getText());

                // Update the table
                ApplicantModel.setValueAt(agent.getFirstName(), selectedRow, 1);
                ApplicantModel.setValueAt(agent.getLastName(), selectedRow, 2);
                ApplicantModel.setValueAt(agent.getEmail(), selectedRow, 3);
                ApplicantModel.setValueAt(agent.getPhoneNumber(), selectedRow, 4);
                ApplicantModel.setValueAt(agent.getAddress(), selectedRow, 5);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Select a Row");
        }
        }
        } catch (Exception ex) {
    ex.printStackTrace();
    JOptionPane.showMessageDialog(null, "Error occurred: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
}


    }//GEN-LAST:event_UpdateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsuranceAdminRoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsuranceAdminRoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsuranceAdminRoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsuranceAdminRoleJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsuranceAdminRoleJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton UpdateBtn;
    private javax.swing.JTable applicantDetailsTable;
    private javax.swing.JTable insEnrollmentsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
