/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.DoctorJPanels;

import Business.Business;
import Doctor.Doctor;
import Hospital.Appointment;
import Hospital.Hospital;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MC
 */
public class DoctorAppointmentsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorAppointmentsJPanel
     */
    public Business business;
    public UserAccount userAccount;
    DefaultTableModel aptsTableModel;
    
    public DoctorAppointmentsJPanel() {
        initComponents();
    }
    
    public DoctorAppointmentsJPanel(Business business, UserAccount userAccount) {
        initComponents();
        this.business = business;
        this.userAccount = userAccount;
        this.aptsTableModel = (DefaultTableModel) docApptsTable.getModel();
        
        displayAppointments();
    }
    
    public void displayAppointments()
    {
        ArrayList<Appointment> aps = this.business.getAppointments().getAppointments();
        if(aps.size() >= 0) {
            aptsTableModel.setRowCount(0);
            for(Appointment a: aps) {
                if (a.getDoctor().getId().equals(userAccount.getPersonId()))
                {
                    Object row[] = new Object[6];
                    row[0] = a.getAppointmentId();
                    row[1] = a.getHospital().getHospitalName();                 
                    row[2] = a.getAppointmentDate();
                    row[3] = a.getAppointmentHour();
                    row[4] = a.getStatus();
                    row[5] = a.getPatient().getFirstName() + ' ' + a.getPatient().getLastName();
                    aptsTableModel.addRow(row);
                }
            }
        }        
    }
    
    public void displayAppointmentsByPatient(String patientName)
    {
        ArrayList<Appointment> aps = this.business.getAppointments().getAppointments();
        if(aps.size() >= 0) {
            aptsTableModel.setRowCount(0);
            for(Appointment a: aps) {
                if (a.getDoctor().getId().equals(userAccount.getPersonId())
                        && a.getPatient().getFirstName().contains(patientName))
                {
                    Object row[] = new Object[6];
                    row[0] = a.getAppointmentId();
                    row[1] = a.getHospital().getHospitalName();                 
                    row[2] = a.getAppointmentDate();
                    row[3] = a.getAppointmentHour();
                    row[4] = a.getStatus();
                    row[5] = a.getPatient().getFirstName() + ' ' + a.getPatient().getLastName();
                    aptsTableModel.addRow(row);
                }
            }
        }        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        docApptsTable = new javax.swing.JTable();
        patientNameSearchField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        docApptsTable.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        docApptsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Apt Id", "Hospital Name", "Date", "Time", "Status", "Patient Name"
            }
        ));
        jScrollPane1.setViewportView(docApptsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 710, 190));

        patientNameSearchField.setBackground(new java.awt.Color(153, 153, 255));
        patientNameSearchField.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        add(patientNameSearchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 250, 30));

        jButton1.setBackground(new java.awt.Color(0, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jButton1.setText("Search by Patient Name");
        jButton1.setBorder(new javax.swing.border.MatteBorder(null));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 182, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("Appointments");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 30));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hospital Management System");
        jPanel1.add(jLabel1);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Hospital Management System");
        jPanel2.add(jLabel5);

        jPanel1.add(jPanel2);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String patientName = patientNameSearchField.getText();
        displayAppointmentsByPatient(patientName);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable docApptsTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField patientNameSearchField;
    // End of variables declaration//GEN-END:variables
}
