/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.ReceptionistJPanels;

import Business.Business;
import UI.MainJFrame;
import UserAccount.UserAccount;
import com.sun.mail.smtp.SMTPMessage;
import java.util.Date;
import java.util.Properties;
import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import javax.swing.JOptionPane;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import javax.activation.FileDataSource;
import javax.mail.BodyPart;
import javax.swing.JOptionPane;
import javax.mail.Session;
import javax.mail.internet.MimeMessage;
import javax.mail.Message;
import javax.mail.Message.RecipientType;
import javax.mail.Multipart;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMultipart;
/**
 *
 * @author divya
 */
public class EmailJFrame extends javax.swing.JFrame {

    /**
     * Creates new form ReceptionistJFrame
     */
     Business business;
UserAccount useraccount;
    public EmailJFrame() {
        initComponents();
    }
 public EmailJFrame(Business business, UserAccount useraccount) {
        initComponents();
        this.setVisible(true);
        this.business = business;
       

        this.useraccount = useraccount;
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bASE64MailboxDecoder1 = new com.sun.mail.imap.protocol.BASE64MailboxDecoder();
        commandFailedException1 = new com.sun.mail.iap.CommandFailedException();
        bASE64MailboxDecoder2 = new com.sun.mail.imap.protocol.BASE64MailboxDecoder();
        messagingException1 = new javax.mail.MessagingException();
        methodNotSupportedException1 = new javax.mail.MethodNotSupportedException();
        newsAddress1 = new javax.mail.internet.NewsAddress();
        parseException1 = new javax.mail.internet.ParseException();
        parseException2 = new javax.mail.internet.ParseException();
        addressException1 = new javax.mail.internet.AddressException();
        authenticationFailedException1 = new javax.mail.AuthenticationFailedException();
        commandFailedException2 = new com.sun.mail.iap.CommandFailedException();
        contentType1 = new javax.mail.internet.ContentType();
        contentType2 = new javax.mail.internet.ContentType();
        folderNotFoundException1 = new javax.mail.FolderNotFoundException();
        illegalWriteException1 = new javax.mail.IllegalWriteException();
        illegalWriteException2 = new javax.mail.IllegalWriteException();
        bASE64MailboxDecoder3 = new com.sun.mail.imap.protocol.BASE64MailboxDecoder();
        newsAddress2 = new javax.mail.internet.NewsAddress();
        messageSet1 = new com.sun.mail.imap.protocol.MessageSet();
        folderNotFoundException2 = new javax.mail.FolderNotFoundException();
        messageRemovedException1 = new javax.mail.MessageRemovedException();
        messageSet2 = new com.sun.mail.imap.protocol.MessageSet();
        parameterList1 = new javax.mail.internet.ParameterList();
        try {
            mailSSLSocketFactory1 = new com.sun.mail.util.MailSSLSocketFactory();
        } catch (java.security.GeneralSecurityException e1) {
            e1.printStackTrace();
        }
        try {
            mailSSLSocketFactory2 = new com.sun.mail.util.MailSSLSocketFactory();
        } catch (java.security.GeneralSecurityException e1) {
            e1.printStackTrace();
        }
        messageRemovedException2 = new javax.mail.MessageRemovedException();
        messageSet3 = new com.sun.mail.imap.protocol.MessageSet();
        methodNotSupportedException2 = new javax.mail.MethodNotSupportedException();
        methodNotSupportedException3 = new javax.mail.MethodNotSupportedException();
        messageSet4 = new com.sun.mail.imap.protocol.MessageSet();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        toMail = new javax.swing.JTextField();
        mesgSubject = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userMessage = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Send Email To Patient");

        jLabel2.setText("To");

        jLabel4.setText("Subject");

        jLabel5.setText("Message");

        userMessage.setColumns(20);
        userMessage.setRows(5);
        jScrollPane1.setViewportView(userMessage);

        jButton1.setText("send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(toMail)
                    .addComponent(mesgSubject)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(287, 287, 287))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(toMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mesgSubject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        jButton2.setText("back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(153, 153, 153))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String to = this.toMail.getText();
       String subject = this.mesgSubject.getText();
       String message = this.userMessage.getText();
       
       if(to.length()==0|| subject.length()== 0|| message.length()==0){
           JOptionPane.showMessageDialog(this, "Provide complete details");}
       
       else{
         
           Properties props = new Properties();

           props.put("mail.smtp.host","smtp.gmail.com");
           props.put("mail.smtp.port","587");
           props.put("mail.smtp.auth","true");

          props.put("mail.smtp.starttls.enable","true");          
           Session session = Session.getDefaultInstance(props, new Authenticator()
                     {
                      @Override
                      protected PasswordAuthentication getPasswordAuthentication(){
                            return new PasswordAuthentication("bostonhospital520@gmail.com","vvhykolxyrykxuuw");
                      }
               
           });
           
           try{
               SMTPMessage sendMessage = new SMTPMessage(session);
               sendMessage.setFrom(new InternetAddress("bostonhospital520@gmail.com"));
               sendMessage.setRecipients(Message.RecipientType.TO,InternetAddress.parse(to));
               //sendMessage.setRecipients(Message.RecipientType.CC,InternetAddress.parse(to));
               sendMessage.setSubject(subject);
               sendMessage.setText(message);              
         
               
               Transport.send(sendMessage);
               
               JOptionPane.showMessageDialog(this,"Sent");
               
               
               
               
               
               
           }catch(Exception ex){
               ex.printStackTrace();
           }
           
           
           
       }
       
       
       
       
       
       
       
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new RecAppointmentsJPanel(business,useraccount);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmailJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.mail.internet.AddressException addressException1;
    private javax.mail.AuthenticationFailedException authenticationFailedException1;
    private com.sun.mail.imap.protocol.BASE64MailboxDecoder bASE64MailboxDecoder1;
    private com.sun.mail.imap.protocol.BASE64MailboxDecoder bASE64MailboxDecoder2;
    private com.sun.mail.imap.protocol.BASE64MailboxDecoder bASE64MailboxDecoder3;
    private com.sun.mail.iap.CommandFailedException commandFailedException1;
    private com.sun.mail.iap.CommandFailedException commandFailedException2;
    private javax.mail.internet.ContentType contentType1;
    private javax.mail.internet.ContentType contentType2;
    private javax.mail.FolderNotFoundException folderNotFoundException1;
    private javax.mail.FolderNotFoundException folderNotFoundException2;
    private javax.mail.IllegalWriteException illegalWriteException1;
    private javax.mail.IllegalWriteException illegalWriteException2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private com.sun.mail.util.MailSSLSocketFactory mailSSLSocketFactory1;
    private com.sun.mail.util.MailSSLSocketFactory mailSSLSocketFactory2;
    private javax.swing.JTextField mesgSubject;
    private javax.mail.MessageRemovedException messageRemovedException1;
    private javax.mail.MessageRemovedException messageRemovedException2;
    private com.sun.mail.imap.protocol.MessageSet messageSet1;
    private com.sun.mail.imap.protocol.MessageSet messageSet2;
    private com.sun.mail.imap.protocol.MessageSet messageSet3;
    private com.sun.mail.imap.protocol.MessageSet messageSet4;
    private javax.mail.MessagingException messagingException1;
    private javax.mail.MethodNotSupportedException methodNotSupportedException1;
    private javax.mail.MethodNotSupportedException methodNotSupportedException2;
    private javax.mail.MethodNotSupportedException methodNotSupportedException3;
    private javax.mail.internet.NewsAddress newsAddress1;
    private javax.mail.internet.NewsAddress newsAddress2;
    private javax.mail.internet.ParameterList parameterList1;
    private javax.mail.internet.ParseException parseException1;
    private javax.mail.internet.ParseException parseException2;
    private javax.swing.JTextField toMail;
    private javax.swing.JTextArea userMessage;
    // End of variables declaration//GEN-END:variables
}
