/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI.CertifyingAuthority;

import Business.Business;
import CertifyingAuthority.TranscriptRequest;
import Course.Course;
import Student.Student;
import UI.MainJFrame;
import UserAccount.UserAccount;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author divya
 */
public class CAJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CAJFrame
     */
    private Business business;
    private UserAccount useraccount;
    DefaultTableModel studentsTableModel;
    
    public CAJFrame(Business business, UserAccount useraccount) {
        initComponents();
        this.business=business;
        this.useraccount=useraccount;
        
        this.studentsTableModel = (DefaultTableModel) studentCreditsTable.getModel();
       this.setVisible(true);
       
       displayRequests();
    }
    
    public void displayRequests()
    {
        ArrayList<TranscriptRequest> transRequests = this.business.getTranscriptRequests().getTranscriptRequests();
        
        if(transRequests.size() >= 0) {
            studentsTableModel.setRowCount(0);
            for(TranscriptRequest c: transRequests) {
                var student = c.getStudent();
                var courses = student.getRegisteredCourses().getCourseList();
                int totalCredits = 0;
                for (Course cr : courses)
                {
                    totalCredits = totalCredits + cr.getCredits();
                }
                Object row[] = new Object[5];
                row[0] = c.getTrId();
                row[1] = student.getStudentId();
                row[2] = student.getName();
                row[3] = totalCredits;
                row[4] = c.getStatus();
                
               studentsTableModel.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        studentCreditsTable = new javax.swing.JTable();
        approveBtn = new javax.swing.JButton();
        declineBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentCreditsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TR ID", "Student ID", "Student Name", "Credits taken", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(studentCreditsTable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 530, 160));

        approveBtn.setText("approve");
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(approveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 320, -1, -1));

        declineBtn.setText("decline");
        declineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                declineBtnActionPerformed(evt);
            }
        });
        getContentPane().add(declineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 320, -1, -1));

        jLabel1.setText("Certification Authority: ABC Services");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        backbtn.setText("back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });
        getContentPane().add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new MainJFrame(business, useraccount);
    }//GEN-LAST:event_backbtnActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        //String studentId = useraccount.getPersonId();
        //Student currentStudent = this.business.getStudentDir().findStudent(studentId);
        int selectedRowIndex = studentCreditsTable.getSelectedRow();
        String trId = studentCreditsTable.getValueAt(selectedRowIndex, 0).toString();
        int totalCredits = Integer.parseInt(studentCreditsTable.getValueAt(selectedRowIndex, 3).toString());
        var currentTR = this.business.getTranscriptRequests().findTranscriptRequest(trId);
        
        if (totalCredits < 8 || currentTR.getStatus().equals("declined"))
        {
            JOptionPane.showMessageDialog(null, "Student hasnt completed the mandatory(8) credits");
        }
        else
        {
            
            currentTR.setStatus("approved");
        }
        
        displayRequests();
    }//GEN-LAST:event_approveBtnActionPerformed

    private void declineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_declineBtnActionPerformed
        int selectedRowIndex = studentCreditsTable.getSelectedRow();
        String trId = studentCreditsTable.getValueAt(selectedRowIndex, 0).toString();
        int totalCredits = Integer.parseInt(studentCreditsTable.getValueAt(selectedRowIndex, 3).toString());
        var currentTR = this.business.getTranscriptRequests().findTranscriptRequest(trId);
        
        if (totalCredits < 8 || currentTR.getStatus().equals("declined"))
        {
            JOptionPane.showMessageDialog(null, "Student hasnt completed the mandatory(8) credits");
        }
        else
        {
            currentTR.setStatus("declined");
        }
        
        displayRequests();
    }//GEN-LAST:event_declineBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CAJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CAJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CAJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CAJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CAJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton declineBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable studentCreditsTable;
    // End of variables declaration//GEN-END:variables
}
